apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: staging-
namespace: staging-app

bases:
- ../base

resources:
  - namespace.yaml
  - ../resources

patches:
- path: patch.yaml
